[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  conditions = {Language = ["en"]}
  from = "/"
  status = 200
  to = "https://tymalik.me"

  [[redirects]]
    conditions = {Language = ["en"]}
    from = "/allArticles"
    status = 200
    to = "https://tymalik.me/allArticles"